# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-30 22:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automotivo', '0002_auto_20161228_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='radio',
            field=models.BooleanField(default=False),
        ),
    ]
